package sistemaeae.gui;


import gnu.io.CommPortIdentifier;
import gnu.io.SerialPort;
import java.awt.GridLayout;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Enumeration;
import java.util.List;
import java.util.Scanner;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import sistemaeae.bean.EAEProfesor;
import sistemaeae.bean.Facultad;
import sistemaeae.bean.Filtro;
import sistemaeae.bean.Imagen;
import sistemaeae.bean.Mes;
import sistemaeae.controller.ControllerDocente;
import sistemaeae.controller.ControllerFacultad;
import sistemaeae.controller.LogController;
import sistemaeae.dao.DocenteDAO;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Admin
 */
public class Main_Frame extends javax.swing.JFrame {

    /**
     * Creates new form Main_Frame
     */
    
    private ControllerDocente docenteController;
    private LogController logController;
    private DocenteDAO docDao;
    String ruta,nombre;
    int contador=0;
    private Imagen imagenes;
    private Imagen imagenesInicio;
     private String rutaProyecto = "C:\\Users\\Freddy Sebastian\\Documents\\Workspaces\\TurtleSoftware\\Classroom RFID System\\";
    //private String rutaProyecto = "C:\\Users\\USER\\Documents\\ELC\\";
    public Main_Frame() {
         
        initComponents();
        
         panelDocentes.setVisible(false);
         panelHistorial.setVisible(false);
         imgAula.setIcon(new ImageIcon(rutaProyecto +"SistemaEAE\\src\\sistemaeae\\gui\\aula.png"));
         imgLampara.setIcon(new ImageIcon(rutaProyecto +"SistemaEAE\\src\\sistemaeae\\gui\\foco.png"));
         imgVentilador.setIcon(new ImageIcon(rutaProyecto +"SistemaEAE\\src\\sistemaeae\\gui\\fan.png"));

         
         docDao = new DocenteDAO();
    }
    
   // My Code
    public void listarDocentes(){
       docenteController = new ControllerDocente();
       this.tbDocente.setModel(docenteController);
    }
    
    public void llenarComboDocente(){
        cmbDocente.removeAllItems();
         docenteController = new ControllerDocente();
        List<EAEProfesor> lst = docenteController.obtenerDocentes();
  
        cmbDocente.addItem(null);
        for(EAEProfesor str : lst) {
           cmbDocente.addItem(str);
        }
    }
    
    
    
    public void listarLog (Filtro fil){
        logController = new LogController(fil);
       this.tbHistorial.setModel(logController);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DesktopPanel = new javax.swing.JPanel();
        panelFooter = new javax.swing.JPanel();
        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        panelInicio = new javax.swing.JPanel();
        pnDocente = new javax.swing.JPanel();
        lblNombre = new java.awt.Label();
        imgFoto = new javax.swing.JLabel();
        label6 = new java.awt.Label();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        imgLampara = new javax.swing.JLabel();
        imgVentilador = new javax.swing.JLabel();
        imgAula = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnIniciarLector = new javax.swing.JToggleButton();
        panelDocentes = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbDocente = new javax.swing.JTable();
        txtNombreDoc = new javax.swing.JTextField();
        txtApellidoDoc = new javax.swing.JTextField();
        txtTituloDoc = new javax.swing.JTextField();
        txtCodigoTarjeta = new javax.swing.JTextField();
        cmbFacultad = new javax.swing.JComboBox();
        txtFecha = new javax.swing.JFormattedTextField();
        label7 = new java.awt.Label();
        label8 = new java.awt.Label();
        label9 = new java.awt.Label();
        label10 = new java.awt.Label();
        label12 = new java.awt.Label();
        label13 = new java.awt.Label();
        imgFotoDoc = new javax.swing.JLabel();
        btnSubirFoto = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        txtImagenDir = new javax.swing.JTextField();
        panelHistorial = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbHistorial = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btnFiltrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbDocente = new javax.swing.JComboBox();
        dtbDesde = new com.toedter.calendar.JDateChooser();
        dtbHasta = new com.toedter.calendar.JDateChooser();
        menuBar = new javax.swing.JMenuBar();
        btnInicio = new javax.swing.JMenu();
        btnConfig = new javax.swing.JMenu();
        btnDocentes = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        btnHistorial = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 650));

        DesktopPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        panelFooter.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        label1.setText("SistemaEAE");

        label2.setText("Todos los derechos reservados 2013 - Creado por: TurtleSoftware / Freddy Ayala");

        javax.swing.GroupLayout panelFooterLayout = new javax.swing.GroupLayout(panelFooter);
        panelFooter.setLayout(panelFooterLayout);
        panelFooterLayout.setHorizontalGroup(
            panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 772, Short.MAX_VALUE)
                .addComponent(label2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelFooterLayout.setVerticalGroup(
            panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelFooterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelFooterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(label2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(label1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        label2.getAccessibleContext().setAccessibleName("Todos los derechos reservados 2013 - Creado por: TurtleSoftware / Freddy Ayala");
        label2.getAccessibleContext().setAccessibleDescription("Todos los derechos reservados 2013 - Creado por: TurtleSoftware / Freddy Ayala");

        panelInicio.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pnDocente.setBorder(javax.swing.BorderFactory.createTitledBorder("Identificador"));

        lblNombre.setText("-.-.-.-");

        imgFoto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        label6.setText("Nombre:");

        javax.swing.GroupLayout pnDocenteLayout = new javax.swing.GroupLayout(pnDocente);
        pnDocente.setLayout(pnDocenteLayout);
        pnDocenteLayout.setHorizontalGroup(
            pnDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnDocenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnDocenteLayout.createSequentialGroup()
                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 92, Short.MAX_VALUE))
                    .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(imgFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        pnDocenteLayout.setVerticalGroup(
            pnDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnDocenteLayout.createSequentialGroup()
                .addGroup(pnDocenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnDocenteLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(label6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE))
                    .addComponent(imgFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lblNombre.getAccessibleContext().setAccessibleName("-.-.-");
        lblNombre.getAccessibleContext().setAccessibleDescription("");

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel1.setText("Sistema EAE");

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel3.setText("AULA 404");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imgAula, javax.swing.GroupLayout.PREFERRED_SIZE, 581, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imgVentilador, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(imgLampara, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(imgAula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(imgLampara, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(imgVentilador, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        btnIniciarLector.setText("INICIAR LECTOR");
        btnIniciarLector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarLectorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelInicioLayout = new javax.swing.GroupLayout(panelInicio);
        panelInicio.setLayout(panelInicioLayout);
        panelInicioLayout.setHorizontalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInicioLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnIniciarLector))
                    .addComponent(pnDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        panelInicioLayout.setVerticalGroup(
            panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInicioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInicioLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(38, 38, 38)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(122, Short.MAX_VALUE))
                    .addGroup(panelInicioLayout.createSequentialGroup()
                        .addComponent(pnDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 172, Short.MAX_VALUE)
                        .addComponent(btnIniciarLector)
                        .addGap(155, 155, 155))))
        );

        pnDocente.getAccessibleContext().setAccessibleName("Docente");

        panelDocentes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbDocente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbDocente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbDocenteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbDocente);

        txtNombreDoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreDocActionPerformed(evt);
            }
        });

        cmbFacultad.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbFacultad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbFacultadActionPerformed(evt);
            }
        });

        txtFecha.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("yyy-MM-dd"))));
        txtFecha.setText("yyyy-mm-dd");
        txtFecha.setToolTipText("");
        txtFecha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFechaActionPerformed(evt);
            }
        });

        label7.setText("Nombre:");

        label8.setText("Titulo:");

        label9.setText("Apellido:");

        label10.setText("Codigo tarjeta:");

        label12.setText("Facultad:");

        label13.setText("Fecha Ingreso:");

        imgFotoDoc.setText("[foto]");
        imgFotoDoc.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnSubirFoto.setText("Subir foto");
        btnSubirFoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubirFotoActionPerformed(evt);
            }
        });

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        txtImagenDir.setEditable(false);
        txtImagenDir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtImagenDirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDocentesLayout = new javax.swing.GroupLayout(panelDocentes);
        panelDocentes.setLayout(panelDocentesLayout);
        panelDocentesLayout.setHorizontalGroup(
            panelDocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDocentesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelDocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDocentesLayout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDocentesLayout.createSequentialGroup()
                        .addGroup(panelDocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelDocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtFecha)
                            .addComponent(txtCodigoTarjeta, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panelDocentesLayout.createSequentialGroup()
                        .addGroup(panelDocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtApellidoDoc)
                            .addComponent(txtNombreDoc)
                            .addComponent(txtTituloDoc)))
                    .addGroup(panelDocentesLayout.createSequentialGroup()
                        .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbFacultad, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(22, 22, 22))
                    .addGroup(panelDocentesLayout.createSequentialGroup()
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnGuardar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDocentesLayout.createSequentialGroup()
                        .addComponent(btnSubirFoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelDocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(imgFotoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtImagenDir, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 965, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelDocentesLayout.setVerticalGroup(
            panelDocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDocentesLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(panelDocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelDocentesLayout.createSequentialGroup()
                        .addComponent(imgFotoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSubirFoto)
                            .addComponent(txtImagenDir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelDocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNombreDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelDocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(label9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtApellidoDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelDocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(label8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTituloDoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelDocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtCodigoTarjeta, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(panelDocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbFacultad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(label12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAgregar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelDocentesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEliminar)
                            .addComponent(btnGuardar)))
                    .addComponent(jScrollPane1))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        panelHistorial.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbHistorial.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tbHistorial);

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel2.setText("Historial de Entrada y Salida");

        btnFiltrar.setText("Filtrar");
        btnFiltrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFiltrarActionPerformed(evt);
            }
        });

        jLabel4.setText("Desde:");

        jLabel5.setText("Hasta:");

        jLabel6.setText("Docente:");

        cmbDocente.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout panelHistorialLayout = new javax.swing.GroupLayout(panelHistorial);
        panelHistorial.setLayout(panelHistorialLayout);
        panelHistorialLayout.setHorizontalGroup(
            panelHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHistorialLayout.createSequentialGroup()
                .addGroup(panelHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHistorialLayout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHistorialLayout.createSequentialGroup()
                        .addGap(94, 94, 94)
                        .addComponent(btnFiltrar))
                    .addGroup(panelHistorialLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addGroup(panelHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbDocente, 0, 140, Short.MAX_VALUE)
                            .addComponent(dtbHasta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dtbDesde, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(138, 138, 138))
        );
        panelHistorialLayout.setVerticalGroup(
            panelHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHistorialLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(panelHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelHistorialLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelHistorialLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(72, 72, 72)
                        .addGroup(panelHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(dtbDesde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(panelHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(dtbHasta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                        .addGroup(panelHistorialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cmbDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(83, 83, 83)
                        .addComponent(btnFiltrar)
                        .addGap(139, 139, 139))))
        );

        javax.swing.GroupLayout DesktopPanelLayout = new javax.swing.GroupLayout(DesktopPanel);
        DesktopPanel.setLayout(DesktopPanelLayout);
        DesktopPanelLayout.setHorizontalGroup(
            DesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelFooter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(DesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(DesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelDocentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(DesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(panelHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        DesktopPanelLayout.setVerticalGroup(
            DesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DesktopPanelLayout.createSequentialGroup()
                .addContainerGap(473, Short.MAX_VALUE)
                .addComponent(panelFooter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10))
            .addGroup(DesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DesktopPanelLayout.createSequentialGroup()
                    .addComponent(panelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(DesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DesktopPanelLayout.createSequentialGroup()
                    .addComponent(panelDocentes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
            .addGroup(DesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(DesktopPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(panelHistorial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        btnInicio.setText("Inicio");
        btnInicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInicioMouseClicked(evt);
            }
        });
        menuBar.add(btnInicio);

        btnConfig.setMnemonic('e');
        btnConfig.setText("Configuracion");

        btnDocentes.setMnemonic('t');
        btnDocentes.setText("Docentes");
        btnDocentes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDocentesMouseClicked(evt);
            }
        });
        btnDocentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocentesActionPerformed(evt);
            }
        });
        btnConfig.add(btnDocentes);

        menuBar.add(btnConfig);

        helpMenu.setMnemonic('h');
        helpMenu.setText("Historial");

        btnHistorial.setMnemonic('c');
        btnHistorial.setText("Ver Historial");
        btnHistorial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHistorialActionPerformed(evt);
            }
        });
        helpMenu.add(btnHistorial);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DesktopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(DesktopPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInicioMouseClicked
        panelHistorial.setVisible(false);
        panelDocentes.setVisible(false);
        panelInicio.setVisible(true);
        
    }//GEN-LAST:event_btnInicioMouseClicked

    private void btnDocentesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDocentesMouseClicked
        
    }//GEN-LAST:event_btnDocentesMouseClicked

    private void btnDocentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocentesActionPerformed
        panelInicio.setVisible(false);
        panelHistorial.setVisible(false);
        panelDocentes.setVisible(true);
        cmbFacultad.removeAllItems();
        
        ArrayList<Facultad> list = new ArrayList<Facultad>();
     
        list.add(new Facultad("1","Ingenieria"));
        list.add(new Facultad("2","Ciencias"));
        list.add(new Facultad("3","Medicina"));
        list.add(new Facultad("4","Humanidades"));
        list.add(new Facultad("5","Comunicaciones"));
       
        
        for(Facultad str : list) {
           cmbFacultad.addItem(str);
        }
        //cmbFacultad.setModel(facController);
        imgFotoDoc.setText("");
        imgFotoDoc.setIcon(new ImageIcon(rutaProyecto + "SistemaEAE\\src\\sistemaeae\\gui\\default.png"));
        listarDocentes();
      
    }//GEN-LAST:event_btnDocentesActionPerformed

    private void btnHistorialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHistorialActionPerformed
        panelHistorial.setVisible(true);
        panelDocentes.setVisible(false);
        panelInicio.setVisible(false);
        llenarComboDocente();
        listarLog(null); //listamos todas
         
    }//GEN-LAST:event_btnHistorialActionPerformed

    private void btnIniciarLectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarLectorActionPerformed
        inicializarConexionArduinoRFID();
        //leerTarjetas();
    }//GEN-LAST:event_btnIniciarLectorActionPerformed

    private void txtImagenDirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtImagenDirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtImagenDirActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        if(tbDocente.getSelectedRow() != -1){
            int x = 0;
            x = tbDocente.getSelectedRow();
            EAEProfesor prof = (EAEProfesor) docenteController.getListaClientes().get(x);
            docenteController.eliminaDocente(prof);

            JOptionPane.showMessageDialog(null, "El Docente fue eliminado Exitosamente", "Hecho", JOptionPane.INFORMATION_MESSAGE);
            imgFotoDoc.setIcon(new ImageIcon(rutaProyecto +"SistemaEAE\\src\\sistemaeae\\gui\\default.png"));
            listarDocentes();
            panelDocentes.updateUI();
        }else{
            JOptionPane.showMessageDialog(null, "Debe seleccionar un docente", "Hecho", JOptionPane.INFORMATION_MESSAGE);

        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed

        if(tbDocente.getSelectedRow() == -1){
            //INSERTAMOS

            EAEProfesor prof = new EAEProfesor();
            prof.setNombre(txtNombreDoc.getText());
            prof.setApellido(txtApellidoDoc.getText());
            prof.setCodigoTarjeta(txtCodigoTarjeta.getText());
            prof.setFacultad(cmbFacultad.getSelectedItem().toString());
            prof.setFechaIngreso(txtFecha.getText());
            prof.setTituloAcademico(txtTituloDoc.getText());
            docenteController.agregarDocente(prof);

            //guardamos imagen
            int id = docenteController.obtenerIDSiguiente();
            if(!ruta.equals("")){
                if(docDao.guardarImagen(ruta,nombre, id)){
                    txtImagenDir.setText("");
                    imgFotoDoc.setIcon(null);
                    //  refrescarCarrusel(0);
                }else{
                    JOptionPane.showMessageDialog(null, "La Imagen no puedo ser Guardada debido al tamaño", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            JOptionPane.showMessageDialog(null, "El Docente fue guardado Exitosamente", "Hecho", JOptionPane.INFORMATION_MESSAGE);
            listarDocentes();
            panelDocentes.updateUI();
        }else{
            //ACTUALIZAMOS
            int x = 0;
            x = tbDocente.getSelectedRow();
            EAEProfesor prof = (EAEProfesor) docenteController.getListaClientes().get(x);
            prof.setNombre(txtNombreDoc.getText());
            prof.setApellido(txtApellidoDoc.getText());
            prof.setCodigoTarjeta(txtCodigoTarjeta.getText());
            prof.setFacultad(cmbFacultad.getSelectedItem().toString());
            prof.setFechaIngreso(txtFecha.getText());
            prof.setTituloAcademico(txtTituloDoc.getText());
            docenteController.modificarDocente(prof);
            if(ruta != null){
            if (!ruta.equals("")) {
                if (docDao.actualizarImagen(ruta, nombre, prof.getIdProfesor())) {
                    txtImagenDir.setText("");
                    imgFotoDoc.setIcon(null);
                    //  refrescarCarrusel(0);
                } else {
                    JOptionPane.showMessageDialog(null, "La Imagen no puedo ser Actualizada debido al tamaño", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            }

            JOptionPane.showMessageDialog(null, "El Docente fue actualizado Exitosamente", "Hecho", JOptionPane.INFORMATION_MESSAGE);
            listarDocentes();
            panelDocentes.updateUI();

        }

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        txtNombreDoc.setText("");
        txtApellidoDoc.setText("");
        txtCodigoTarjeta.setText("");
        txtFecha.setText("");
        txtTituloDoc.setText("");
        tbDocente.clearSelection();
        imgFotoDoc.setIcon(null);
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnSubirFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubirFotoActionPerformed
        final JFileChooser elegirImagen = new JFileChooser();
        elegirImagen.setMultiSelectionEnabled(false);
        int o = elegirImagen.showOpenDialog(this);
        if(o == JFileChooser.APPROVE_OPTION){
            ruta = elegirImagen.getSelectedFile().getAbsolutePath();
            nombre = elegirImagen.getSelectedFile().getName();
            txtImagenDir.setText(ruta);
            Image preview = Toolkit.getDefaultToolkit().getImage(ruta);
            if(preview != null){
                imgFotoDoc.setText("");
                ImageIcon icon = new ImageIcon(preview.getScaledInstance(imgFotoDoc.getWidth(), imgFotoDoc.getHeight(), Image.SCALE_DEFAULT));
                imgFotoDoc.setIcon(icon);
            }
        }
    }//GEN-LAST:event_btnSubirFotoActionPerformed

    private void txtFechaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFechaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFechaActionPerformed

    private void cmbFacultadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbFacultadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbFacultadActionPerformed

    private void txtNombreDocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreDocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreDocActionPerformed

    private void tbDocenteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbDocenteMouseClicked
        int x = 0;
        x = tbDocente.getSelectedRow();
        EAEProfesor prof = (EAEProfesor) docenteController.getListaClientes().get(x);
        txtNombreDoc.setText(prof.getNombre());
        txtApellidoDoc.setText(prof.getApellido());
        txtCodigoTarjeta.setText(prof.getCodigoTarjeta());
        txtFecha.setText(prof.getFechaIngreso());
        txtTituloDoc.setText(prof.getTituloAcademico());

        for (int z= 0 ; z < cmbFacultad.getItemCount(); z++){
            Facultad fac = (Facultad) cmbFacultad.getItemAt(z);

            if(fac.getNombre().equals(prof.getFacultad())){
                cmbFacultad.setSelectedIndex(z);
            }
        }
        imagenes = docDao.getImagenes(prof.getIdProfesor());
        ImageIcon icon;
        if(imagenes.getImagen() !=null){
            icon = new ImageIcon(imagenes.getImagen().getScaledInstance(imgFotoDoc.getWidth(), imgFotoDoc.getHeight(), Image.SCALE_DEFAULT));
        }else{
            icon = new ImageIcon(rutaProyecto +"SistemaEAE\\src\\sistemaeae\\gui\\default.png");
        }
        imgFotoDoc.setText("");
        imgFotoDoc.setIcon(icon);
        panelDocentes.updateUI();

    }//GEN-LAST:event_tbDocenteMouseClicked

    private void btnFiltrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFiltrarActionPerformed
     
     tbHistorial.removeAll();
     SimpleDateFormat fmt = new SimpleDateFormat("yyyy-MM-dd");
     EAEProfesor prof = (EAEProfesor) cmbDocente.getSelectedItem();
      String diaDesde = null;
      String diaHasta = null;
      String nombre = null;
      String apellido = null;
      
      if (dtbDesde.getDate() !=null  )
        if(dtbDesde.getDate() !=null ){
           diaDesde= fmt.format(dtbDesde.getDate()); 
        }
        if(dtbHasta.getDate() !=null){
           diaHasta = fmt.format(dtbHasta.getDate());
        }
        
       
      if(prof != null )  {
         nombre = prof.getNombre();
         apellido = prof.getApellido();
      }
      Filtro fil = new Filtro(diaDesde, diaHasta,nombre,apellido);
      listarLog(fil);
        
      
    }//GEN-LAST:event_btnFiltrarActionPerformed

    
    // -------------------------COMUNICACION CON ARDUINO-----------------------------------------------------
    private OutputStream output = null;
    private InputStream input = null;
    SerialPort serialPort;
    private final String PUERTO = "COM17";
    private static final int TIMEOUT = 2000; //Milisegundos
    private static final int DATA_RATE = 9600;
    private List listaDocentes;
    boolean estado = false;
    boolean encendido = false;
    // Clase en la que está el código a ejecutar 
    TimerTask timerTask = new TimerTask() {
        public void run() {
            leerTarjetas();

        }
    };
    // Aquí se pone en marcha el timer cada segundo. 
    Timer timer = new Timer();
    TimerTask timerTask2 = new TimerTask() {
        public void run() {
          //  label1.setText("Sistema de Seguridad");
            //jLabel1.setIcon(new ImageIcon("C:\\Users\\USER\\Desktop\\Arduino---Java---JavaDuino-master\\Arduino---Java---JavaDuino-master\\Tutorial JAVADUINO - Código Java\\src\\system.jpg"));
        }
    };
    // Aquí se pone en marcha el timer cada segundo. 
    Timer timer2 = new Timer();
    
    public void obtenerTodosDocentes(){
         docenteController = new ControllerDocente();
      listaDocentes =  docenteController.obtenerDocentes();
    }

    public void inicializarConexionArduinoRFID() {
        
        //Primero obtenemos docentes disponibles
        obtenerTodosDocentes();
        CommPortIdentifier puertoID = null;
        
        
        Enumeration puertoEnum = CommPortIdentifier.getPortIdentifiers();

        while (puertoEnum.hasMoreElements()) {
            CommPortIdentifier actualPuertoID = (CommPortIdentifier) puertoEnum.nextElement();
            if (PUERTO.equals(actualPuertoID.getName())) {
                puertoID = actualPuertoID;
                break;
            }
        }

        if (puertoID == null) {
            mostrarError("No se puede conectar al puerto");
            //System.exit(ERROR);
            
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog (null, "Desea ingresar el numero de tarjeta manualmente?","Warning",dialogButton);
            if(dialogResult == JOptionPane.YES_OPTION){
                  leerCodigoDocenteManual();
            }
            return;
        }

        try {
            serialPort = (SerialPort) puertoID.open(this.getClass().getName(), TIMEOUT);
            //Parámetros puerto serie

            serialPort.setSerialPortParams(DATA_RATE, SerialPort.DATABITS_8, SerialPort.STOPBITS_1, SerialPort.PARITY_NONE);

            output = serialPort.getOutputStream();
            input = serialPort.getInputStream();

            timer.scheduleAtFixedRate(timerTask, 0, 500);
            timer2.scheduleAtFixedRate(timerTask2, 0, 3000);
            
            logController = new LogController(null);
        } catch (Exception e) {
            mostrarError(e.getMessage());
            System.exit(ERROR);

        }
    }
    public  void leerCodigoDocenteManual() {
        JTextField field1 = new JTextField("");
      
        JPanel panel = new JPanel(new GridLayout(0, 1));
       
        panel.add(new JLabel("Ingresar codigo de tarjeta:"));
        panel.add(field1);

        int result = JOptionPane.showConfirmDialog(null, panel, "Sistema EAE",
            JOptionPane.OK_CANCEL_OPTION, JOptionPane.PLAIN_MESSAGE);
        if (result == JOptionPane.OK_OPTION) {
            System.out.println("ID Manual #" + field1.getText());
            String serieTarjeta = field1.getText();
            procesarTarjeta(serieTarjeta);
        } else {
            System.out.println("Cancelled");
        }
    }
    
    String tarjetaAnterior = "100";

    public void leerTarjetas() {
        // System.out.println("...");
        
       

        try {

            input = serialPort.getInputStream();
            //mientras es diferente a -1 que leea el puerto USB , si es -1 no lo leera y continuara el conteo
            if (input.read() != -1) {

               String serie = new Scanner(input, "UTF-8").useDelimiter("\\.").next();
            //String serieQuemada = "125,189,55,44,219";
          // String  serie = serieQuemada;
               System.out.println(serie);
                
                // MOSTRAMOS PROFESOR
                if (serie.length() > 2) {
                    procesarTarjeta(serie);
                }



            }
        } catch (Exception ex) {
            Logger.getLogger(Main_Frame.class.getName()).log(Level.SEVERE, null, ex);
        }


    }

    public void mostrarError(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "ERROR", JOptionPane.ERROR_MESSAGE);
    }
    
    public void procesarTarjeta(String serie){
            EAEProfesor docente = null;
                                             
                    docente = docDao.obtenerDocentePorCodigo(serie);
                    System.out.println("estado: "+encendido);
                     if(encendido)
                        {
                            if(serie.equals("189,170,158,201,64")){ //189,170,158,201,64
                                JOptionPane.showMessageDialog(null, "Llave maestra reconocida , desactivando sistema... ", "Informacion", JOptionPane.INFORMATION_MESSAGE);
                                imgLampara.setIcon(new ImageIcon(rutaProyecto + "SistemaEAE\\src\\sistemaeae\\gui\\foco.png"));
                                imgVentilador.setIcon(new ImageIcon(rutaProyecto + "SistemaEAE\\src\\sistemaeae\\gui\\fan.png"));
                                imgFoto.setIcon(new ImageIcon(rutaProyecto + "SistemaEAE\\src\\sistemaeae\\gui\\default.png"));
                                imgFoto.setIcon(new ImageIcon(rutaProyecto + "SistemaEAE\\src\\sistemaeae\\gui\\default.png"));
                                 encendido = false; 
                            }
                           
                        }    

                    if (docente != null) {




                        System.out.println("Encontramos a :" + docente.getNombre() + " " + docente.getApellido());


                        lblNombre.setText(docente.getNombre() + " " + docente.getApellido());

                        //cargar imagenes

                        imagenesInicio = docDao.getImagenes(docente.getIdProfesor());
                        ImageIcon icon;
                        if (imagenesInicio.getImagen() != null) {
                            icon = new ImageIcon(imagenesInicio.getImagen().getScaledInstance(imgFoto.getWidth(), imgFoto.getHeight(), Image.SCALE_DEFAULT));
                        } else {
                            icon = new ImageIcon(rutaProyecto + "SistemaEAE\\src\\sistemaeae\\gui\\default.png");
                        }
                        imgFoto.setText("");
                        imgFoto.setIcon(icon);
                        
                                           
                        

                        if (tarjetaAnterior.equals(serie)) {
                            //SALIDA
                            
                            tarjetaAnterior = "100";
                            JOptionPane.showMessageDialog(null, "Adios " + docente.getNombre() + " " + docente.getApellido(), "Informacion", JOptionPane.INFORMATION_MESSAGE);
                            imgLampara.setIcon(new ImageIcon(rutaProyecto + "SistemaEAE\\src\\sistemaeae\\gui\\foco.png"));
                            imgVentilador.setIcon(new ImageIcon(rutaProyecto + "SistemaEAE\\src\\sistemaeae\\gui\\fan.png"));
                            imgFoto.setIcon(new ImageIcon(rutaProyecto + "SistemaEAE\\src\\sistemaeae\\gui\\default.png"));
                            imgFoto.setIcon(new ImageIcon(rutaProyecto + "SistemaEAE\\src\\sistemaeae\\gui\\default.png"));

                            lblNombre.setText("-.-.-.-");
                            
                            //actualizamos salida en el log
                            logController.modificarLog();
                            encendido = false;

                        } else {
                            //ENTRADA
                            JOptionPane.showMessageDialog(null, "Bienvenido " + docente.getNombre() + " " + docente.getApellido(), "Informacion", JOptionPane.INFORMATION_MESSAGE);
                            imgLampara.setIcon(new ImageIcon(rutaProyecto + "SistemaEAE\\src\\sistemaeae\\gui\\focoEncendido.png"));
                            imgVentilador.setIcon(new ImageIcon(rutaProyecto + "SistemaEAE\\src\\sistemaeae\\gui\\fanEncendido.png"));
                            tarjetaAnterior = docente.getCodigoTarjeta();
                            encendido = true;
                            //insertamos en el log
                            logController.agregarLog(docente.getIdProfesor());
                        }
                        //BANDERA
                        if (!tarjetaAnterior.equals("100")) {
                            tarjetaAnterior = docente.getCodigoTarjeta();
                        }


                        panelInicio.updateUI();
                        estado = true;



                    }else{
                         mostrarError("Codigo Invalido!");
                    }
    }



    
    
    //-------------------------------------------------------------------------------------------------------
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Frame().setVisible(true);
              
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel DesktopPanel;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JMenu btnConfig;
    private javax.swing.JMenuItem btnDocentes;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnFiltrar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JMenuItem btnHistorial;
    private javax.swing.JToggleButton btnIniciarLector;
    private javax.swing.JMenu btnInicio;
    private javax.swing.JButton btnSubirFoto;
    private javax.swing.JComboBox cmbDocente;
    private javax.swing.JComboBox cmbFacultad;
    private com.toedter.calendar.JDateChooser dtbDesde;
    private com.toedter.calendar.JDateChooser dtbHasta;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JLabel imgAula;
    private javax.swing.JLabel imgFoto;
    private javax.swing.JLabel imgFotoDoc;
    private javax.swing.JLabel imgLampara;
    private javax.swing.JLabel imgVentilador;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label12;
    private java.awt.Label label13;
    private java.awt.Label label2;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.Label lblNombre;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JPanel panelDocentes;
    private javax.swing.JPanel panelFooter;
    private javax.swing.JPanel panelHistorial;
    private javax.swing.JPanel panelInicio;
    private javax.swing.JPanel pnDocente;
    private javax.swing.JTable tbDocente;
    private javax.swing.JTable tbHistorial;
    private javax.swing.JTextField txtApellidoDoc;
    private javax.swing.JTextField txtCodigoTarjeta;
    private javax.swing.JFormattedTextField txtFecha;
    private javax.swing.JTextField txtImagenDir;
    private javax.swing.JTextField txtNombreDoc;
    private javax.swing.JTextField txtTituloDoc;
    // End of variables declaration//GEN-END:variables
}
